export const GET_CHATROOMS_REQUEST = "GET_CHATROOMS_REQUEST";
export const GET_CHATROOMS_SUCCESS = "GET_CHATROOMS_SUCCESS";
export const GET_CHATROOMS_ERROR = "GET_CHATROOMS_ERROR";

export const GET_SUPPORT_CHATS_REQUEST = "GET_SUPPORT_CHATS_REQUEST";
export const GET_SUPPORT_CHATS_SUCCESS = "GET_SUPPORT_CHATS_SUCCESS";
export const GET_SUPPORT_CHATS_ERROR = "GET_SUPPORT_CHATS_ERROR";

export const GET_DISCUSSION_CHATS_REQUEST = "GET_DISCUSSION_CHATS_REQUEST";
export const GET_DISCUSSION_CHATS_SUCCESS = "GET_DISCUSSION_CHATS_SUCCESS";
export const GET_DISCUSSION_CHATS_ERROR = "GET_DISCUSSION_CHATS_ERROR";

export const GET_ACTIVE_CHATS_REQUEST = "GET_ACTIVE_CHATS_REQUEST";
export const GET_ACTIVE_CHATS_SUCCESS = "GET_ACTIVE_CHATS_SUCCESS";
export const GET_ACTIVE_CHATS_ERROR = "GET_ACTIVE_CHATS_ERROR";