export const SIGN_IN_WITH_EMAIL_REQUEST = "SIGN_IN_WITH_EMAIL_REQUEST";
export const SIGN_IN_WITH_EMAIL_SUCCESS = "SIGN_IN_WITH_EMAIL_SUCCESS";
export const SIGN_IN_WITH_EMAIL_ERROR = "SIGN_IN_WITH_EMAIL_ERROR";

export const STORE_PHONE_NUMBER = "STORE_PHONE_NUMBER";

export const SIGN_UP_WITH_EMAIL_REQUEST = "SIGN_UP_WITH_EMAIL_REQUEST";
export const SIGN_UP_WITH_EMAIL_SUCCESS = "SIGN_UP_WITH_EMAIL_SUCCESS";
export const SIGN_UP_WITH_EMAIL_ERROR = "SIGN_UP_WITH_EMAIL_ERROR";

export const SIGN_UP_PROCESSS_NAVIGATE = "SIGN_UP_PROCESSS_NAVIGATE";
export const SIGN_UP_PROCESSS_NAVIGATE_SUCCESS = "SIGN_UP_PROCESSS_NAVIGATE_SUCCESS";

export const SIGN_UP_PROCESSS_DATA = "SIGN_UP_PROCESSS_DATA";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";

export const HOME_STACK_NAVIGATE = "HOME_STACK_NAVIGATE";
export const UPDATE_USER = "UPDATE_USER";
export const LOG_OUT = "LOG_OUT";