export const GET_JOBS_REQUEST = "GET_JOBS_REQUEST";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_ERROR = "GET_JOBS_ERROR";

export const GET_JOB_INVITES_REQUEST = "GET_JOB_INVITES_REQUEST";
export const GET_JOB_INVITES_SUCCESS = "GET_JOB_INVITES_SUCCESS";
export const GET_JOB_INVITES_ERROR = "GET_JOB_INVITES_ERROR";

export const GET_HOME_DATA_REQUEST = "GET_HOME_DATA_REQUEST";
export const GET_HOME_DATA_SUCCESS = "GET_HOME_DATA_SUCCESS";
export const GET_HOME_DATA_ERROR = "GET_HOME_DATA_ERROR";